= MEGA

Make End-of-the-month-process Great Again!

== Prerequisites

=== Project setup

- Java 11
- Maven 3.5+

See link:mega-zep-connector/README.adoc[README of ZEP-Connector] for more information.

./mega-zep-backend/config/application.properties (externalized configurations)
[source,properties]
----
## COMMON ##
mega.image.logo.url=<YOUR_LOGO_URL>
mega.wiki.eom.url=<YOUR_EOM_URL>

## ZEP ##
zep.soap.token=***

## MAIL ##
quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
quarkus.mailer.from=<MAIL_FROM>
quarkus.mailer.host=<MAIL_HOST>
quarkus.mailer.port=<MAIL_PORT>
quarkus.mailer.ssl=<SSL_ENABLED>
quarkus.mailer.username=<MAIL_ACCOUNT_USERNAME>
quarkus.mailer.password=<MAIL_ACCOUNT_PASSWORD>
quarkus.mailer.mock=false

mega.mail.firstbusinessday.reminder=<MAIL_REMINDER_MAIL>

## TEST USER ##
mega.test.googleuser.email=<USER_EMAIL>
mega.test.googleuser.id=<USER_ID>
----

=== Google OAuth2 client setup

See link:https://developers.google.com/identity/protocols/OAuth2UserAgent[here] for a description how to setup a google oauth client.

== Dockerfiles

These are the Dockerfiles used by this project

* link:docker/agent-nodejs/Dockerfile[agent-nodejs/Dockerfile] +
 The Dockerfile for building the nodejs build agent
* link:docker/agent-quarkus/Dockerfile[agent-quarkus/Dockerfile] +
 The Dockerfile for building the quarkus build agent

== Openshift Dev Project

.google-secrets.properties (google related configurations)
[source,properties]
----
# Used by the frontend for two factor authentication
oauth.clientId=<GOOGLE_OAUTH_CLIENT_ID>
----

.Secrets
[source,bash]
----
# Create github login secret (username, password are the properties)
oc create secret generic mega-git-http --from-env-file=mega-dev-github.properties --type=kubernetes.io/basic-auth
oc annotate secret mega-git-http jenkins.openshift.io/secret.name=mega-git-http
oc label secret mega-git-http credential.sync.jenkins.openshift.io=true

# Create mega secret for service and jenkins
oc create secret generic mega-secrets --from-file=filename=mega-secrets.properties
oc annotate secret mega-secrets jenkins.openshift.io/secret.name=mega-secrets
oc label secret mega-secrets credential.sync.jenkins.openshift.io=true

# Create google secret for frontend build
oc create secret generic google-secrets --from-file=filename=google-secrets.properties
oc annotate secret google-secrets jenkins.openshift.io/secret.name=google-secrets
oc label secret google-secrets credential.sync.jenkins.openshift.io=true

# Create git ssh secret
oc create secret generic mega-git-ssh --from-file=ssh-privatekey=mega-dev.ssh.key --type=kubernetes.io/ssh-auth -n 57-mega-dev
oc annotate secret mega-git-ssh jenkins.openshift.io/secret.name=mega-git-ssh
oc label secret mega-git-ssh credential.sync.jenkins.openshift.io=true
----

.Persistence Volumes
[source,bash]
----
# Persistence Volumes for caching repositories
oc create -f  .\ocp\maven-pvc.yaml -n 57-mega-dev
----

.Build Configurations
[source,bash]
----
# Binary build for backend uber jar
oc new-build --binary=true --name=mega-zep-backend --docker-image=docker.io/fabric8/s2i-java:3.0-java11 -n 57-mega-dev
oc set triggers bc/mega-zep-backend --remove-all -n 57-mega-dev

# Binary build for frontend html content
oc new-build httpd:2.4 --binary=true --name=mega-zep-frontend -n 57-mega-dev
oc set triggers bc/mega-zep-frontend --remove-all -n 57-mega-dev

# Quarkus Build Agent
oc new-build https://github.com/Gepardec/mega.git#develop --name=quarkus-build-agent --context-dir=docker/agent-quarkus --source-secret=mega-git-http -n 57-mega-dev
oc set triggers bc/quarkus-build-agent --remove-all -n 57-mega-dev

# Nodejs Build Agent
oc new-build https://github.com/Gepardec/mega.git#feature/ocp-builds --name=nodejs-build-agent --context-dir=docker/agent-nodejs --source-secret=mega-git-http -n 57-mega-dev
oc set triggers bc/nodejs-build-agent --remove-all -n 57-mega-dev
----

== Openshift Test/Prod Project

.Secrets
[source,bash]
----
oc create secret generic mega-secrets --from-file=filename=mega-secrets.properties
----

.Cleanup
[source,bash]
----
oc process --filename mega-zep-backend.yaml --param-file=mega-zep-backend.dev.properties --param=IMAGE_STREAM_TAG=latest | oc delete -f -
oc process --filename mega-zep-frontend.yaml --param-file=mega-zep-frontend.dev.properties --param=IMAGE_STREAM_TAG=latest | oc delete -f -
----

WARNING: Ensure that the configuration is properly setup for your environment

TODOS:

. quarkus-build-agent build config needs to point to develop after merge
. nodejs-build-agent build config needs to point to develop after merge
. Only deploy to Openshift if it's the ``develop`` branch
. Get jenkins multibranch config.xml and add it to the jenkins s2i build