kind: "Template"
apiVersion: "v1"
metadata:
  name: "jenkins-custom"
  annotations:
    openshift.io/display-name: "Jenkins slaves"
    description: "Jenkins slaves"
    iconClass: "icon-jenkins"
    tags: "jenkins"

parameters:
  - name: "GIT_URL"
    displayName: "Git url"
    description: "The git url of the repository holding the S2I resources"
    required: true

  - name: "GIT_REF"
    displayName: "Git ref"
    description: "The git ref of the repository holding the S2I resources"
    required: true

  - name: "APP"
    displayName: "App label"
    description: "The value for the label app"
    required: true

objects:
  - kind: "ImageStream"
    apiVersion: "v1"
    metadata:
      name: "jenkins-s2i"
      labels:
        app: "${APP}"
    spec:
      lookupPolicy:
        local: true
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: 'docker.io/openshift/jenkins-2-centos7:v3.11'

  - kind: "ImageStream"
    apiVersion: "v1"
    metadata:
      name: "jenkins-custom"
      labels:
        app: "${APP}"

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: custom-jenkins-build
    spec:
      source:  
        contextDir: "s2i/jenkins"                     
        git:
          uri: "${GIT_URL}"
          ref: "${GIT_REF}"
        type: Git
      strategy:                     
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: jenkins-s2i:latest
        type: Source
      output:                       
        to:
          kind: ImageStreamTag
          name: jenkins-custom:latest
      triggers:
        - type: "ImageChange" 
        - type: "ConfigChange"
          imageChange: {}