kind: "Template"
apiVersion: "v1"
metadata:
  name: "jenkins-slaves"
  annotations:
    openshift.io/display-name: "Jenkins slaves"
    description: "Jenkins slaves"
    iconClass: "icon-jenkins"
    tags: "jenkins"

parameters:
  - name: "GIT_URL"
    displayName: "Git url"
    description: "The git url of the repository holding the slave resources"
    required: true

  - name: "GIT_REF"
    displayName: "Git ref"
    description: "The git ref of the repository holding the slave resources"
    required: true

  - name: "APP"
    displayName: "App label"
    description: "The value for the label app"
    required: true

  - name: "MAVEN_VERSION"
    displayName: "MAven Version"
    description: "The maven version to use"
    required: true

objects:
  - kind: "ImageStream"
    apiVersion: "v1"
    metadata:
      name: "jenkins-slave-base"
      labels:
        role: "jenkins-slave"
        app: "${APP}"
    spec:
      tags:
        - name: "latest"
          labels:
            role: "jenkins-slave"
            app: "${APP}"
          annotations:
            openshift.io/display-name: "Jenkins Slave Base"
            description: "The jenkins slave base"
            iconClass: "icon-jenkins"
            tags: "slave-base"
            version: "3.7"
          from:
            kind: "DockerImage"
            name: "docker.io/openshift/jenkins-slave-base-centos7:3.10"


  ######################
  # Jenkins JDK8 Slave #
  ######################
  - kind: "ImageStream"
    apiVersion: "v1"
    metadata:
      name: "jenkins-slave-maven"
      labels:
        role: "jenkins-slave"
        app: "${APP}"
    spec:
      tags:
        - name: "latest"
          labels:
            role: "jenkins-slave"
            app: "${APP}"
          annotations:
            openshift.io/display-name: "Jenkins Slave Maven"
            description: "The jenkins slave maven"
            iconClass: "icon-jenkins"
            tags: "slave-maven"
            version: "3.7"
          from:
            kind: "DockerImage"
            name: "docker.io/openshift/jenkins-slave-maven-centos7:3.10"
"