apiVersion: v1
kind: Template
metadata:
  name: mega-zep-frontend
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      generation: 1
      labels:
        app: "${APP}"
      name: "${NAME}"
    spec:
      replicas: 1
      selector:
        app: "${APP}"
        deploymentconfig: "${NAME}"
      strategy:
        activeDeadlineSeconds: 21600
        rollingParams:
          intervalSeconds: 1
          timeoutSeconds: 60
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            app: "${APP}"
            deploymentconfig: "${NAME}"
        spec:
          containers:
            - image: " "
              imagePullPolicy: Always
              name: "${NAME}"
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: "${CPU}"
                  memory: "${MEMORY}"
                requests:
                  cpu: "${CPU}"
                  memory: "${MEMORY}"
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - "${NAME}"
            from:
              kind: ImageStreamTag
              name: "${IMAGE_STREAM_TAG}"
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: "${APP}"
      name: "${NAME}"
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: "${APP}"
        deploymentconfig: "${NAME}"
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      annotations:
        openshift.io/host.generated: "true"
      creationTimestamp: null
      labels:
        app: "${APP}"
      name: "${NAME}"
    spec:
      port:
        targetPort: 8080
      tls:
        termination: edge
      to:
        kind: Service
        name: "${NAME}"
        weight: 100
      wildcardPolicy: None
parameters:
  - name: "APP"
    displayName: "The app label"
    required: true
  - name: "NAME"
    displayName: "The resource name"
    required: true
  - name: "CPU"
    displayName: "The cpu count to use. E.g.: 500m"
    required: true
  - name: "MEMORY"
    displayName: "The memory count to use. E.g.: 512Mi"
    required: true
  - name: "IMAGE_STREAM_TAG"
    displayName: "The image stream tag to use. E.g.: mega-zep-backend:latest"
    required: true