apiVersion: v1
kind: Template
metadata:
  name: mega-zep-backend
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: "${APP}"
      name: "${NAME}"
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: "${APP}"
        deploymentconfig: "${NAME}"
      strategy:
        activeDeadlineSeconds: 21600
        rollingParams:
          timeoutSeconds: 120
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          labels:
            app: "${APP}"
            deploymentconfig: "${NAME}"
        spec:
          containers:
            - env:
                - name: AB_JOLOKIA_OFF
                  value: "true"
                - name: AB_PROMETHEUS_OFF
                  value: "true"
                - name: JAVA_MAX_MEM_RATIO
                  value: "95"
                - name: JAVA_OPTIONS
                  value: "${JAVA_OPTIONS}"
              image: ""
              imagePullPolicy: Always
              name: "${NAME}"
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8778
                  protocol: TCP
                - containerPort: 9779
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - curl
                    - -sSf
                    - http://localhost:8080/health/ready
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: "${CPU}"
                  memory: "${MEMORY}"
                requests:
                  cpu: "${CPU}"
                  memory: "${MEMORY}"
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /deployments/config/application.properties
                  name: config
                  subPath: filename
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          volumes:
            - name: config
              secret:
                defaultMode: 420
                secretName: "${SECRET}"
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - "${NAME}"
            from:
              kind: ImageStreamTag
              name: "${IMAGE_STREAM_TAG}"
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: "${APP}"
      name: "${NAME}"
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: 8778-tcp
          port: 8778
          protocol: TCP
          targetPort: 8778
        - name: 9779-tcp
          port: 9779
          protocol: TCP
          targetPort: 9779
      selector:
        app: "${APP}"
        deploymentconfig: "${NAME}"
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      annotations:
        openshift.io/host.generated: "true"
      creationTimestamp: null
      labels:
        app: "${APP}"
      name: "${NAME}"
    spec:
      port:
        targetPort: 8080
      tls:
        termination: edge
      to:
        kind: Service
        name: "${NAME}"
        weight: 100
      wildcardPolicy: None
parameters:
  - name: "APP"
    displayName: "The app label"
    required: true
  - name: "NAME"
    displayName: "The resource name"
    required: true
  - name: "JAVA_OPTIONS"
    displayName: "The java options"
    required: false
  - name: "CPU"
    displayName: "The cpu count to use. E.g.: 500m"
    required: true
  - name: "MEMORY"
    displayName: "The memory count to use. E.g.: 512Mi"
    required: true
  - name: "SECRET"
    displayName: "The secret providing the configuration"
    required: true
  - name: "IMAGE_STREAM_TAG"
    displayName: "The image stream tag to use. E.g.: mega-zep-backend:latest"
    required: true