#!groovy

pipeline {
    agent {
        kubernetes {
            cloud 'openshift'
            yamlFile "./jenkins/src/build/openjdk-11-build-pod.yaml"
        }
    }
    parameters {
        string(name: 'Password', defaultValue: '')
    }

    stages {
        stage("Skopeo") {
            steps {
                container('quarkus') {
                    sh "skopeo copy --src-tls-verify=false \
                                    --dest-tls-verify=false \
                                    --src-creds openshift:\$(oc whoami -t) \
                                    --dest-creds=gdhet:${params.Password} \
                                    docker://docker-registry.default.svc:5000/57-mega-dev/mega-zep-frontend:latest \
                                    docker://registry.hub.docker.com/gdhet/mega-zep-backend:latest"
                }
            }
        }
    }
}
