#!groovy

pipeline {
    agent {
        kubernetes {
            cloud 'openshift'
            yamlFile "./jenkins/src/build/openjdk-11-build-pod.yaml"
        }
    }
    parameters {
        string(name: 'Password', defaultValue: '')
    }

    stages {
        stage("Skopeo") {
            steps {
                container('quarkus') {
                    sh "skopeo copy --dest-creds=gdhet:${params.Password} docker-registry.default.svc:5000/mega-dev/mega-zep-frontend:latest registry.hub.docker.com/gdhet/mega-zep-backend:latest"
                }
            }
        }
    }
}
